### ISSUE TITLE
Write up the README.md 

### ISSUE THREAD

**Issue by elderj** [elderj/MeteoRadar#5]
Add content to the `README.md` file. At the moment it is looking a little sparse.

Should have basic documentation for how to use the app, what it does.

**Comment by htjjen** [comment]
Hi @elderj ,
May I help you to add more information in the README.md? If so, would you please provide me some details so I can write up these sections?

--------------
Background:
As a beginner contributor, I'm working on an assignment for my technical writing course, which requires students to make real-world revisions and have them accepted.

I will make PR(s) after my revisions. Please feel free to correct me if I missed anything. Thank you!

**Comment by elderj** [comment]
Hi @htjjen, I actually just closed this issue with a pretty basic `README.md`, but will write up another one tomorrow for a more detailed `README.md` for my project if you are interested. Thanks!

**Comment by htjjen** [comment]
Hi @elderj , thank you for your reply! Sure. If you could provide me with some key information, I can write it up for you. Thanks again!
