### ISSUE TITLE
Re-Design of the README.md file

### ISSUE THREAD

**Issue by elderj** [elderj/MeteoRadar#6]
The current `README.md` file is quite basic to say the least an could use additional information for those involved with the development and ultimately the end-users of the application.

Add information for the following:
- [ ] Features:
  - [ ] Weather for the current location (Done automatically)
  - [ ] Weather for a specified location via zip code (Done by entering in a US zip code)
  - [ ] Hourly and future forecast for both above (This bit is still under development)
*This weather info comes from OpenWeatherMap.com*

- [ ] How to get the app:
  - [ ] During the beta release, 
  - [ ] the app will not yet be available on the app store, but the `apk` install (which will require users to enable dev app in the `development settings` options of their android device will be available via GitHub and may be posted on reddit under a beta testing sub-reddit.

  - [ ] After the beta release the app will be available via the app store and should be able to be found by searching "MeteoRadar"

**Comment by elderj** [comment]
Hi @htjjen I added you as a collaborator to the project and created a `develop` branch along with this new issue. Please let me know what questions you have! Thanks!

**Comment by htjjen** [comment]
Hi @elderj , thank you very much for the opportunity! 

I'm wondering whether we can start with the basic information, such as Getting Started/How to Use or Install, what is needed before installation (Prerequisites), Features, etc. Perhaps I can put any features you're working on in the Under Development section of the README, etc. 

Please provide me with more details so I can write it up as a start. 

------
P.S. The deadline for my assignment is coming up within a week and it's essential for me to have my pull request approved and merged. I'm hoping I can draft the above sections in the next couple days so you would have time to review before my deadline. Would that be okay? Thank you again in advance!

**Comment by htjjen** [comment]
@elderj  Thanks for adding the details. 

I've added some info into the README. I've added a prerequisite (i.e. Android device) but please feel free to let me know if it's incorrect. Please let me know if you'd like me to change other changes and/or add anything else. Thank you!

**Comment by elderj** [comment]
@htjjen  Glad that was enough for you to go off of. I think since the app is still pretty basic at the moment the changes you made to the README look pretty good. I appreciate your input! Let me know if you happen to need anything else!

**Comment by htjjen** [comment]
@elderj  Thank you very much for the opportunity!
